[tools]
go = "1.27.1"
gofumpt = "0.12.0"
golangci-lint = "2.14.0"

[tasks.build]
run = "go build ./..."

[tasks.test]
run = "go test ./..."

[tasks.fmt]
run = "gofumpt -extra -w ."

[tasks.lint]
run = "golangci-lint run"

[tasks.check]
depends = ["fmt", "build", "test", "lint"]
